---
- name: Pull Docker image for Node.js app
  docker_image:
    name: node:14
    state: present

- name: Create a directory for the app
  file:
    path: /home/ubuntu/app
    state: directory

- name: Copy the app files to the server
  copy:
    src: /path/to/your/app
    dest: /home/ubuntu/app/
  tags: deploy

- name: Run Docker container for Node.js app
  docker_container:
    name: nodejs_app
    image: node:14
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/app:/usr/src/app
    state: started
    restart_policy: always
  tags: deploy
