---
- hosts: droplets
  become: yes
  roles:
    - docker_install

- hosts: droplets
  become: yes
  tasks:
    - name: Pull Wiki.js image
      docker_image:
        name: lscr.io/linuxserver/wikijs:latest
        state: present
      tags:
        - pull_image

    - name: Run Wiki.js container
      docker_container:
        name: wikijs
        image: lscr.io/linuxserver/wikijs:latest
        state: started
        ports:
          - 3000:3000
      tags:
        - run_container
