---
- name: Install Docker and dependencies
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce

- name: Check if Docker GPG key is already added
  command: apt-key list | grep Docker
  register: docker_gpg_key_check
  ignore_errors: yes

- name: Check if Docker repository is already added
  command: grep -r docker /etc/apt/sources.list /etc/apt/sources.list.d/
  register: docker_repo_check
  ignore_errors: yes

- name: Install Docker Python library
  pip:
    name: docker
    state: present
